spring:
  application:
    name: experis-test
  h2:
    console:
      enabled: true
      path: /h2-database
  datasource:
    url: jdbc:h2:mem:experisdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9001
  servlet:
    context-path: /${spring.application.name}
    
api:
  swagger:
    tittle: Experis Test Services Documentation
    description: This document describes the API methods for microservices operations.
    version: 1.0.0
    contact:
      name: Dhavian Fernando Hernandez
      url: https://www.example.com/
      email: dfernando1124@hotmail.com
    service:
      rootpath: /${spring.application.name}
      name: Experis Demo
    base-package: co.com.experis.test